//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPogodi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewPogodi.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500,1000,10000,50000,100000,250000,500000,1000000.
        /// </summary>
        internal static string CHECKPOINTS {
            get {
                return ResourceManager.GetString("CHECKPOINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.8.
        /// </summary>
        internal static string DEFAULT_SCORE_FONT_SIZE {
            get {
                return ResourceManager.GetString("DEFAULT_SCORE_FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string EXTRA_BONUS_POINTS_PER_SECOND {
            get {
                return ResourceManager.GetString("EXTRA_BONUS_POINTS_PER_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        internal static string EXTRA_FALL_RATE_FACTOR {
            get {
                return ResourceManager.GetString("EXTRA_FALL_RATE_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.
        /// </summary>
        internal static string EXTRA_SIGNATURE_FALL_RATE_FACTOR {
            get {
                return ResourceManager.GetString("EXTRA_SIGNATURE_FALL_RATE_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.015.
        /// </summary>
        internal static string EXTRA_SIGNATURE_PROBABILITY {
            get {
                return ResourceManager.GetString("EXTRA_SIGNATURE_PROBABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        internal static string EXTRA_SPAWN_RATE_FACTOR {
            get {
                return ResourceManager.GetString("EXTRA_SPAWN_RATE_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.14.
        /// </summary>
        internal static string FALL_RATE_ACCELERATION {
            get {
                return ResourceManager.GetString("FALL_RATE_ACCELERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string FALL_RATE_STARTING {
            get {
                return ResourceManager.GetString("FALL_RATE_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string MAX_SCORE_FONT_SIZE {
            get {
                return ResourceManager.GetString("MAX_SCORE_FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string PENALTY {
            get {
                return ResourceManager.GetString("PENALTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string REWARD {
            get {
                return ResourceManager.GetString("REWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.4.
        /// </summary>
        internal static string SCORE_SIZE_ANIMATION_DURATION {
            get {
                return ResourceManager.GetString("SCORE_SIZE_ANIMATION_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.08.
        /// </summary>
        internal static string SCORE_SIZE_ANIMATION_DURATION_FASTEST {
            get {
                return ResourceManager.GetString("SCORE_SIZE_ANIMATION_DURATION_FASTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.
        /// </summary>
        internal static string SPAWN_RATE {
            get {
                return ResourceManager.GetString("SPAWN_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string TICK_INTERVAL {
            get {
                return ResourceManager.GetString("TICK_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string TIP_DURATION {
            get {
                return ResourceManager.GetString("TIP_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.8.
        /// </summary>
        internal static string TIP_FADE_OUT_DURATION {
            get {
                return ResourceManager.GetString("TIP_FADE_OUT_DURATION", resourceCulture);
            }
        }
    }
}
